Feature Branch With all the created methods
wandji20/Enumerables- pull request #1
Opened 2020-11-23 11:19 UTC by od-c0d3r

Methods Created :

1. my_each

2020-11-23 11:46 UTC, mahmoud717 requested changes
### Changes required ♻️ 

**Hello @od-c0d3r & @wandji20**

Great job with the project so far, but there are still some changes to be made:
 
---
### Requested 🔴 

- [x] please check the inline comments
---

please make these changes and request another code review.

if you have any questions don't hesitate to contact me on slack **MahmoudMohammad**

2020-11-23 11:46 UTC, mahmoud717 commented on main.rb
> +  end
- [ ] my_each returns an Enumerator if no block is given

2020-11-23 11:46 UTC, mahmoud717 commented on main.rb
> +  end
- [ ] my_each_with_index returns an enumerator if no block is given

2020-11-23 11:46 UTC, mahmoud717 commented on main.rb
> +  end
- [ ] my_select returns an enumerator if no block is given

2020-11-23 11:46 UTC, mahmoud717 commented on main.rb
> +  end
- [ ] my_all? when no block or argument is given returns true when none of the collection members are false or nil

- [ ] my_all? when no block or argument is given returns false when one of the collection members are false or nil

- [ ] my_all? when a class is passed as an argument returns true if all of the collection is a member of such class::Integer

- [ ] enumerables #my_all? when a class is passed as an argument returns true if all of the collection is a member of such class::Numeric

- [ ] enumerables #my_all? when a class is passed as an argument returns false if any of the collection is not a member of such class

- [ ] enumerables #my_all? when a Regex is passed as an argument returns true if all of the collection matches the Regex

- [ ] my_all? when a Regex is passed as an argument returns false if any of the collection does not match the Regex

- [ ] my_all? when a pattern other than Regex or a Class is given returns true if all of the collection matches the pattern

- [ ] my_all? when a pattern other than Regex or a Class is given returns false if any of the collection does not match the pattern

2020-11-23 11:46 UTC, mahmoud717 commented on main.rb
> +  end
- [ ] my_any? when no block or argument is given returns false if at least one of the collection is not true

- [ ] my_any? when a class is passed as an argument returns true if at least one of the collection is a member of such class::Numeric

- [ ] my_any? when no block or argument is given returns true if at least one of the collection is not false or nil

- [ ] my_any? when a class is passed as an argument returns true if at least one of the collection is a member of such class::Integer

- [ ] my_any? when a Regex is passed as an argument returns true if any of the collection matches the Regex

- [ ] my_any? when a Regex is passed as an argument returns false if none of the collection matches the Regex

- [ ] my_any? when a pattern other than Regex or a Class is given returns false if none of the collection matches the pattern

- [ ] my_any? when a pattern other than Regex or a Class is given returns true if any of the collection matches the pattern

2020-11-23 11:46 UTC, mahmoud717 commented on main.rb
> +  end
- [ ] my_none? when no block or argument is given returns true only if none of the collection members is true

- [ ] my_none? when no block or argument is given returns false only if one of the collection members is true

- [ ] my_none? when a class is passed as an argument returns true if none of the collection is a member of such class

- [ ] my_none? when a class is passed as an argument returns true if none of the collection is a member of such class::Numeric

- [ ] my_none? when a class is passed as an argument returns false if any of the collection is a member of such class

- [ ] my_none? when a Regex is passed as an argument returns true if none of the collection matches the Regex

- [ ] my_none? when a Regex is passed as an argument returns false if any of the collection matches the Regex

- [ ] my_none? when a pattern other than Regex or a Class is given returns true only if none of the collection matches the pattern

- [ ] my_none? when a pattern other than Regex or a Class is given returns false only if one of the collection matches the pattern

2020-11-23 11:46 UTC, mahmoud717 commented on main.rb
> +  # my_count
- [ ] my_count counts the number of items in enum that are equal to item if an argument is given

- [ ] my_count counts the number of elements yielding a true value if a block is given

2020-11-23 11:46 UTC, mahmoud717 commented on main.rb
> +  end
- [ ] my_map returns an Enumerator if no block is given

2020-11-23 11:46 UTC, mahmoud717 commented on main.rb
> +  end
- [ ] my_inject raises a "LocalJumpError" when no block or argument is given

- [ ] my_inject searches for the longest word in an array of strings

- [ ] my_inject does not mutate the original array

- [ ] my_inject when a block is given without an initail value combines all elements of enum by applying a binary operation, specified by a block

- [ ] my_inject when a block is given without an initail value combines all elements of enum by applying a binary operation, specified by a block::range

- [ ] my_inject when a block is given with an initail value combines all elements of enum by applying a binary operation, specified by a block

- [ ] my_inject when a symbol is specified with an initail value combines each element of the collection by applying the symbol as a named method

- [ ] my_inject when a symbol is specified with an initail value combines each element of the collection by applying the symbol as a named method::range

2020-11-23 17:07 UTC, od-c0d3r commented
Thank you @mahmoud717 for the review ⭐️
we are working on it and
considering pushing ASAP.

2020-11-24 12:50 UTC, od-c0d3r commented
After the last review we added :

- For my_each, my_each_with_index, my_select, my_map
Returns an Enumerator if no block is given 

- For my_all?, my_any, my_none
Accepts blocks and arguments as a class, regex, or a pattern 

- For my_count
Counts the number of items that equal to the given argument.

2020-11-24 12:59 UTC, umairarshadbutt approved these changes
# Status: REQUIRED CHANGES :warning: :construction: 

Hi @od-c0d3r  and @wandji20 
Good job with the changes! :tada: We are almost there.
We, however, do have a few changes to carry out before we proceed (see review comment).

##

 For this project, work on the suggested changes  👇.
- [x] Rename the file name from `main.rb` to `enumerables.rb`
- [x] #my_all? when a pattern other than Regex or a Class is given returns false if any of the collection does not match the pattern
- [x] #my_any? when no block or argument is given returns true if at least one of the collection is not false or nil
- [x] #my_none? returns false if the block ever returns true for all elements
- [x] #my_none? returns false if the block ever returns true for all elements::range
- [x] #my_none? when a pattern other than Regex or a Class is given returns false only if one of the collection matches the pattern
- [x] #my_inject raises a "LocalJumpError" when no block or argument is given
- [x] #my_inject when a block is given without an initail value combines all elements of enum by applying a binary operation, specified by a block::range
- [x] #my_inject when a block is given with an initial value combines all elements of enum by applying a binary operation, specified by a block
- [x] #my_inject when a symbol is specified without an initial value combines each element of the collection by applying the symbol as a named method
- [x] #my_inject when a symbol is specified without an initail value combines each element of the collection by applying the symbol as a named method:range
- [ ] #multiply_els accepts an array as an argument and multiplies all the elements of the array together using #my_inject

##
- **When you have made the specified changes, please submit another code review. Thank you!**
##
**If you are stuck at any point or have any questions, let me know by leaving a comment here and mentioning me. I will be happy to help**
HAPPY CODING :computer:
**[Umair Arshad](https://umairarshad.me/)**
[Twitter](https://twitter.com/its_UmairArshad) | [LinkedIn](https://www.linkedin.com/in/umair-arshad-butt/) | [GitHub](https://github.com/umairarshadbutt)

2020-11-24 13:10 UTC, od-c0d3r commented
Thanks for the review @umairarshadbutt 

We care working on it and Pushing ASAP

2020-11-24 15:38 UTC, PhillipUg requested changes
Hey team, 👋

You have done a great job on this project so far! However, you still need to make some changes before we can approve this request 👇🏿 

### Changes Required ♻️ 

- [ ] Some of your methods like `my_any`, `my_none`, and `my_inject`are still failing. So I am going to give you sample test cases below. Make sure they all pass.
```
# 5. my_any? (example test cases)
puts 'my_any?'
puts '-------'
p [7, 10, 3, 5].my_any?(&:even?) # => true
p [7, 10, 4, 5].my_any?(&:even?) # => true
p %w[q r s i].my_any? { |char| 'aeiou'.include?(char) } # => true
p [7, 11, 3, 5].my_any?(&:even?) # => false
p %w[q r s t].my_any? { |char| 'aeiou'.include?(char) } # => false
# test cases required by tse reviewer
p [3, 5, 4, 11].my_any? # => true
p [1, nil, false].my_any?(1) # => true
p [1, nil, false].my_any?(Integer) # => true
p %w[dog door rod blade].my_any?(/z/) # => false
p [1, 2, 3].my_any?(1) # => true
puts

# 6. my_none? (example test cases)
puts 'my_none?'
puts '--------'
p [3, 5, 7, 11].my_none?(&:even?) # => true
p %w[sushi pizza burrito].my_none? { |word| word[0] == 'a' } # => true
p [3, 5, 4, 7, 11].my_none?(&:even?) # => false
p %w[asparagus sushi pizza apple burrito].my_none? { |word| word[0] == 'a' } # => false
# test cases required by tse reviewer
p [1, 2, 3].my_none? # => false
p [1, 2, 3].my_none?(String) # => true
p [1, 2, 3, 4, 5].my_none?(2) # => false
p [1, 2, 3].my_none?(4) # => true
puts

# 9. my_inject
puts 'my_inject'
puts '---------'
p [1, 2, 3, 4].my_inject(10) { |accum, elem| accum + elem } # => 20
p [1, 2, 3, 4].my_inject { |accum, elem| accum + elem } # => 10
p [5, 1, 2].my_inject('+') # => 8
p (5..10).my_inject(2, :*) # should return 302400
p (5..10).my_inject(4) { |prod, n| prod * n } # should return 604800
```

#### Please, make all REQUIRED changes and submit your request again! 😀

If you have any questions, feel free to send me a message through Slack as **Phillip Musiime**
I would be happy to help! 👩‍💻 

Happy coding 🤓

2020-11-25 06:50 UTC, od-c0d3r commented
Thank you @PhillipUg for the review ⭐️⭐️⭐️

Your provided test cases helped us identify the weak point in the code.

2020-11-25 11:24 UTC, andresporras3423 requested changes
### Status: Changes Required :recycle:
**Hello Rashad Rashad & Wandji Wandji** 
Good job with the improvements to your project :muscle:  :muscle:
It meets most of the requirements :clap: :clap: :clap:  
There are just a few problems to correct before you can go ahead:

- [x] #my_inject raises a 'LocalJumpError' when no block or argument is given
    ```
    begin
      [1,2,3,4].my_inject
    rescue LocalJumpError
      true
    end
    ```

- [x] #my_inject when a block is given without an initail value combines all elements of enum
by applying a binary operation, specified by a block::range
      `(1..3).inject(&proc{|total, num| total*num}) == (1..3).my_inject(&proc{|total, num| total*num})`
- [x] #my_inject when a symbol is specified without an initail value combines each element of
the collection by applying the symbol as a named method
      `[1,2,3].inject(:+) == [1,2,3].my_inject(:+)`
- [ ] #my_inject when a symbol is specified without an initail value combines each element of
the collection by applying the symbol as a named method:range
      `(1..9).inject(:+) == (1..9).my_inject(:+)`
- [ ] #multiply_els accepts an array as an argument and multiplies all the elements of the array together using #my_inject
    `multiply_els([1,2,3]) == 6`
- [x] In the README file, you explain user has to run the main.rb file, but you don't have a file with that name in your project.
 
Please request another review once you are ready! :+1: 
 
Happy coding :relaxed:
 
Oscar Andrés Russi Porras

2020-11-25 18:23 UTC, voscarmv requested changes
# Nice work so far, team. 👍 
## However, there are some changes required 👀 🧰 🔨 🔧 

- Please read my code comments in order to fix the errors found in your methods!

### Submit these changes and request a new code review! 😄 👍 

### Questions or comments? Reach me on [Twitter](https://twitter.com/voscarmv) or [LinkedIn](https://linkedin.com/in/oscar-mier) 🧑‍💻🗨️🧑‍💻 
# Happy Hacking! 🧠 ⌨️ 🖱️ 🖥️

2020-11-25 18:23 UTC, voscarmv commented on enumerables.rb
> +end
Your `my_inject` method returned the following errors:

```
Failures:

  1) enumerables #my_inject searches for the longest word in an array of strings
     Failure/Error: expect(words.my_inject(&search)).to eq words.inject(&search)
     
       expected: "blade"
            got: 5
     
       (compared using ==)
     # ./spec/enumerables_spec.rb:410:in `block (3 levels) in <top (required)>'

  2) enumerables #my_inject does not mutate the original array
     Failure/Error: array.my_inject { |num| num + 1 }
     
     NoMethodError:
       undefined method `init' for #<Array:0x00005637cd6c4d68>
     # ./enumerables.rb:155:in `my_inject'
     # ./spec/enumerables_spec.rb:414:in `block (3 levels) in <top (required)>'

  3) enumerables #my_inject when a block is given without an initail value combines all elements of enum by applying a binary operation, specified by a block
     Failure/Error: expect(array.my_inject(&operation)).to eq array.inject(&operation)
     
     NoMethodError:
       undefined method `init' for #<Array:0x00005637cd7bd670>
     # ./enumerables.rb:155:in `my_inject'
     # ./spec/enumerables_spec.rb:420:in `block (4 levels) in <top (required)>'

  4) enumerables #my_inject when a block is given without an initail value combines all elements of enum by applying a binary operation, specified by a block::range
     Failure/Error: actual = range.my_inject { |prod, n| prod * n }
     
     NoMethodError:
       undefined method `init' for 5..50:Range
     # ./enumerables.rb:155:in `my_inject'
     # ./spec/enumerables_spec.rb:424:in `block (4 levels) in <top (required)>'

  5) enumerables #my_inject when a block is given with an initail value combines all elements of enum by applying a binary operation, specified by a block
     Failure/Error: actual = range.my_inject(4) { |prod, n| prod * n }
     
     NoMethodError:
       undefined method `init' for 5..50:Range
     # ./enumerables.rb:155:in `my_inject'
     # ./spec/enumerables_spec.rb:432:in `block (4 levels) in <top (required)>'
```

Here's an explanation of each of these error messages:

1)  Your `my_inject` is returning the wrong output here. It should return the value of the longest word, not the number of letters in it. You may test your code in the following manner to make sure it outputs the correct value:

```
search = proc { |memo, word| memo.length > word.length ? memo : word }
words = %w[dog door rod blade] 
words.my_inject(&search) # This should return "blade"
```

2) 3) 4) 5) Apparently, you have a bug in line 155 in your `enumerables.rb` file. Please make sure that the `init` method you are using here exists for the cases. You may use the following setup for testing these cases:

```
array = [5, 4, 3, 2, 1]
range =   Range.new(5, 50)
operation = proc { |sum, n| sum + n }
array_clone = array.clone 

# Make sure the following calls to `my_inject` don't produce an `method init not found` error:
array.my_inject { |num| num + 1 }
array.my_inject(&operation)
range.my_inject { |prod, n| prod * n }
range.my_inject(4) { |prod, n| prod * n }
```

2020-11-25 19:32 UTC, od-c0d3r commented
Thank you @voscarmv ⭐️⭐️⭐️
Well, descriptive and oriented review.
And yes for 2,3,4,5 was a missing indentation 😇

2020-11-25 19:42 UTC, voscarmv approved these changes
# Project status: Approved ✨ 😎👍 💯 ✔️
### You may merge this branch and move forward ⛙🛣
### Questions or comments? Reach me on [Twitter](https://twitter.com/voscarmv) or [LinkedIn](https://linkedin.com/in/oscar-mier) 🧑‍💻🗨️🧑‍💻 
# Happy Hacking! 🧠 ⌨️ 🖱️ 🖥️

2020-11-25 20:04 UTC, merged